apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: streamotion-java
    context: .
    docker:
      network: host
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/kayosportsau/streamotion-java:corretto-{{.VERSION}}'
  local: {}
  